runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /pages
    static_dir: pages
  - url: /js
    static_dir: js
  - url: /website-styles
    static_dir: website-styles
  - url: /.*
    script: main.app

libraries:
  - name: jinja2
    version: latest
